# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'

  # web
  config.vm.define :engrsm do |engrsm|
    engrsm.vm.hostname = 'staging.engrsm.com'
    engrsm.vm.network :private_network, ip: '192.168.33.10', virtualbox__intnet: 'intnet'
    engrsm.vm.network :forwarded_port, guest: 22, host: 2222, host_ip: '127.0.0.1', id: 'ssh', auto_correct: true
  end

  # jenkins
  config.vm.define :deploy do |deploy|
    deploy.vm.hostname = 'deploy.server'
    deploy.vm.network :private_network, ip: '192.168.33.20', virtualbox__intnet: 'intnet'
    deploy.vm.network :forwarded_port, guest: 22, host: 2200, host_ip: '127.0.0.1', id: 'ssh', auto_correct: true
  end
end
