# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # dependent
  config.vm.box = 'centos/7'

  # network
  config.vm.network 'private_network', ip: '192.168.33.10'

  # name
  config.vm.hostname = 'staging.engrsm.com'
  config.vm.define 'engrsm' do |engrsm|
  end
  config.vm.provider :virtualbox do |v|
    v.name = 'engrsm'
  end
end
