# Redis session store settings
default: &default
  port: 6379
  #  password: <%= ENV['REDIS_PASSWORD'] %>
  db: <%= ENV['REDIS_DB'] %>
  namespace: session_my100tales
  expire_after: 10.days

development:
  <<: *default
  host: 127.0.0.1
  namespace: session_my100tales_development

# TODO
test:
  <<: *default

# TODO
staging:
  <<: *default

# TODO
production:
  <<: *default
