# Redis session store settings
default: &default
  port: 6379
  #  password: <%= ENV['REDIS_PASSWORD'] %>
  db: <%= ENV['REDIS_DB'] %>
  namespace: session_engrsm
  expire_after: 10.days

development:
  <<: *default
  host: 127.0.0.1
  namespace: session_engrsm_development

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
